Feature/dockerizacion
udistrital/plan_adquisiciones_crud pull request #7
Opened 2020-11-04 22:20 UTC by Jeisson005

Issue #4

2020-11-05 21:09 UTC, BOTOOM requested changes
no te lo puedo aprobar ya que si esta doquerizado pero su conexion a la base de datos no es exitosa, adjunto imagen de un sistema que si esta compilando

![image](https://user-images.githubusercontent.com/28914781/98295952-3d522280-1f80-11eb-948f-7980b5df0738.png)

Posiblemente tengas lios ya que aun no tienes migraciones y podrías de momento omitir ese paso, realiza los ajustes para que al compilarse se pueda conectar a la base de datos, se puede saber que no se realizo la conexión según lo que muestra la consola ya que mostrara algún error o mostrara lo siguiente

![image](https://user-images.githubusercontent.com/28914781/98296460-f3b60780-1f80-11eb-8541-c498acd99f58.png)

la linea que dice `[ORM]2020/11/05 20:58:18 register db Ping `default`, pq: SSL is not enabled on the server` . Esta linea indica que no se puedo realizar conexión a la base de datos

2020-11-05 21:09 UTC, BOTOOM commented on main.go
> +	orm.RegisterDataBase("default", "postgres",
esto debe de ir en una sola linea ya que esta mandando error de compilación del api

2020-11-06 04:27 UTC, Jeisson005 commented on main.go
> +	orm.RegisterDataBase("default", "postgres",
Se agrega migrations y se corrigen los problemas con la conexión a la base de datos

2020-11-06 08:04 UTC, BOTOOM approved these changes

2020-11-06 08:04 UTC, merged